// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghuhptabsovhkfavfpiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodWhwdGFic292aGtmYXZmcGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Nzk1ODQsImV4cCI6MjA1ODQ1NTU4NH0.y_zLCW8L_VG3hSy9u1YlLtMPj-Eo_lOm0fTb-cBVdaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);